# Site settings
title: home
email: nazola0@koraetech.ac.kr

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
